#!/usr/bin/env bash
# Configures the Nginx server so that /redirect_me redirects to another page
# it is configured as a "301 Moved Permantly"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etcnginx/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 http://cuberule.com/;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
