#!/usr/bin/env bash
#configure web-02 to be identical to web-01


sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Page not found" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-By $HostName;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://en.wikipedia.org/wiki/HTTP_301#:~:text=HTTP%20301%20is%20the%20HTTP,this%20response%20should%20be%20updated.;
}
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
