#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
ssh -i ~/.ssh/school ubuntu@a3904fa9dfad@a3904fa9dfad.87aefeab.alx-cod.online
